ControleVacinas - MVC ASP-NET/Controllers/ListaDeCadastrosController.cs
using ControleVacinas___MVC_ASP_NET.Filters;
using ControleVacinas___MVC_ASP_NET.Helper;
using ControleVacinas___MVC_ASP_NET.Models;
using ControleVacinas___MVC_ASP_NET.Repositorio;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using static iTextSharp.text.pdf.events.IndexEvents;
using System.Net;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection.Metadata;
using Document = iTextSharp.text.Document;
using System.Runtime.Intrinsics.X86;
using System.IO;
using System.Xml.Linq;
using static ControleVacinas___MVC_ASP_NET.Repositorio.ListaDeCadastrosRepositorio;
using iTextSharp.xmp.impl;
using Org.BouncyCastle.Pqc.Crypto.Lms;
using iTextSharp.text.pdf.codec.wmf;
using iTextSharp.text.pdf.hyphenation;
using System.Text;

namespace ControleVacinas___MVC_ASP_NET.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ListaDeCadastrosController : Controller
    {
        private readonly IListaDeCadastrosRepositorio _listaDeCadastrosRepositorio;
        private readonly ISessao _sessao;
        public ListaDeCadastrosController(IListaDeCadastrosRepositorio listaDeCadastrosRepositorio,
                                          ISessao sessao)
        {
            _listaDeCadastrosRepositorio = listaDeCadastrosRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            _listaDeCadastrosRepositorio.CalcularTotalTiposDeVacinasTodosCadastros();

            _listaDeCadastrosRepositorio.CalcularTotalDosesTodosCadastros();

            //// Inicializa o valor do Enum (SituacaoVacinacao)
            //var situacaoVacinacao = ControleVacinas___MVC_ASP_NET.Enums.SituacaoVacinacaoEnum.VacinacaoCompleta;

            //// Armazenar o valor do Enum no ViewBag
            //ViewBag.SituacaoVacinacao = situacaoVacinacao;


            // Calcular os totais em relação aos servidores
            var balanco = _listaDeCadastrosRepositorio.CalcularBalancoDeVacinacaoDosServidores();

            //// Armazenar os valores no ViewBag            
            //ViewBag.totalServidoresCadastrados = balanco.totalServidoresCadastrados;
            //ViewBag.totalVacinadosCompletamente = balanco.totalVacinadosCompletamente;
            //ViewBag.totalVacinadosParcialmente = balanco.totalVacinadosParcialmente;
            //ViewBag.totalNaoVacinados = balanco.totalNaoVacinados;

            // Verificar se está vazio ou nulo e atribuir null se for o caso
            ViewBag.totalServidoresCadastrados = balanco?.totalServidoresCadastrados ?? (int?)null;
            ViewBag.totalVacinadosCompletamente = balanco?.totalVacinadosCompletamente ?? (int?)null;
            ViewBag.totalVacinadosParcialmente = balanco?.totalVacinadosParcialmente ?? (int?)null;
            ViewBag.totalNaoVacinados = balanco?.totalNaoVacinados ?? (int?)null;


            //try
            //{
            //    // Carregar os dados para a ViewBag
            //    CarregarBalancoVacinacao();

            //    // Aqui você pode passar outros dados necessários para a View
            //    return View();
            //}
            //catch (Exception erro)
            //{
            //    TempData["MensagemErro"] = $"Ops, ocorreu um erro: {erro.Message}";
            //    return RedirectToAction("Index");
            //}


            // Calcular os totais de cada dose de todas as vacinas (todo o banco)
            var totaisPorDose = _listaDeCadastrosRepositorio.CalcularTotaisPorDose();

            // Armazenar os valores no ViewBag
            ViewBag.TotalDose1HepatiteB = totaisPorDose.TotalDose1HepatiteB;
            ViewBag.TotalDose2HepatiteB = totaisPorDose.TotalDose2HepatiteB;
            ViewBag.TotalDose3HepatiteB = totaisPorDose.TotalDose3HepatiteB;
            ViewBag.TotalReforcoHepatiteB = totaisPorDose.TotalReforcoHepatiteB;

            ViewBag.TotalExameAntiHBS = totaisPorDose.TotalExameAntiHBS;
            ViewBag.TotalResultadoAntiHBS = totaisPorDose.TotalResultadoAntiHBS;

            ViewBag.TotalDose1DifteriaTetano = totaisPorDose.TotalDose1DifteriaTetano;
            ViewBag.TotalDose2DifteriaTetano = totaisPorDose.TotalDose2DifteriaTetano;
            ViewBag.TotalDose3DifteriaTetano = totaisPorDose.TotalDose3DifteriaTetano;
            ViewBag.TotalReforcoDifteriaTetano = totaisPorDose.TotalReforcoDifteriaTetano;

            ViewBag.TotalDose1TripliceViral = totaisPorDose.TotalDose1TripliceViral;
            ViewBag.TotalDose2TripliceViral = totaisPorDose.TotalDose2TripliceViral;

            ViewBag.TotalDose1Covid = totaisPorDose.TotalDose1Covid;
            ViewBag.TotalDose2Covid = totaisPorDose.TotalDose2Covid;
            ViewBag.TotalDose3Covid = totaisPorDose.TotalDose3Covid;
            ViewBag.TotalReforco1Covid = totaisPorDose.TotalReforco1Covid;
            ViewBag.TotalReforco2Covid = totaisPorDose.TotalReforco2Covid;

            ViewBag.TotalDoseUnicaFebreAmarela = totaisPorDose.TotalDoseUnicaFebreAmarela;
            ViewBag.TotalDoseAnualInfluenza = totaisPorDose.TotalDoseAnualInfluenza;

            // Calcular os totais de cada tipo de vacina (todo o banco)
            var totaisPorVacina = _listaDeCadastrosRepositorio.CalcularTotaisPorVacina();

            ViewBag.TotalHepatiteB = totaisPorVacina.TotalHepatiteB;
            ViewBag.TotalExameAntiHBS = totaisPorVacina.TotalExameAntiHBS;
            ViewBag.TotalDifteriaTetano = totaisPorVacina.TotalDifteriaTetano;
            ViewBag.TotalTripliceViral = totaisPorVacina.TotalTripliceViral;
            ViewBag.TotalCovid = totaisPorVacina.TotalCovid;
            ViewBag.TotalFebreAmarela = totaisPorVacina.TotalFebreAmarela;
            ViewBag.TotalInfluenza = totaisPorVacina.TotalInfluenza;


            // Obter a menor e maior data de cada coluna de datas no banco
            //var datasMinMax = _listaDeCadastrosRepositorio.ObterMinMaxDatas();
            //ViewBag.datasMinMax = datasMinMax;

            // Obter as datas mínimas e máximas do repositório
            var datasMinMax = _listaDeCadastrosRepositorio.ObterMinMaxDatas();

            // Converter as datas para o formato "yyyy-MM-dd"
            var datasMinMaxFormatadas = new
            {
                MinDataNascimento = datasMinMax.MinDataNascimento?.ToString("yyyy-MM-dd"),
                MaxDataNascimento = datasMinMax.MaxDataNascimento?.ToString("yyyy-MM-dd"),
                MinDataDose1HepatiteB = datasMinMax.MinDataDose1HepatiteB?.ToString("yyyy-MM-dd"),
                MaxDataDose1HepatiteB = datasMinMax.MaxDataDose1HepatiteB?.ToString("yyyy-MM-dd"),
                MinDataDose2HepatiteB = datasMinMax.MinDataDose2HepatiteB?.ToString("yyyy-MM-dd"),
                MaxDataDose2HepatiteB = datasMinMax.MaxDataDose2HepatiteB?.ToString("yyyy-MM-dd"),
                MinDataDose3HepatiteB = datasMinMax.MinDataDose3HepatiteB?.ToString("yyyy-MM-dd"),
                MaxDataDose3HepatiteB = datasMinMax.MaxDataDose3HepatiteB?.ToString("yyyy-MM-dd"),
                MinDataDoseReforcoHepatiteB = datasMinMax.MinDataDoseReforcoHepatiteB?.ToString("yyyy-MM-dd"),
                MaxDataDoseReforcoHepatiteB = datasMinMax.MaxDataDoseReforcoHepatiteB?.ToString("yyyy-MM-dd"),
                MinDataExameAntiHBS = datasMinMax.MinDataExameAntiHBS?.ToString("yyyy-MM-dd"),
                MaxDataExameAntiHBS = datasMinMax.MaxDataExameAntiHBS?.ToString("yyyy-MM-dd"),
                MinDataDose1DifteriaTetano = datasMinMax.MinDataDose1DifteriaTetano?.ToString("yyyy-MM-dd"),
                MaxDataDose1DifteriaTetano = datasMinMax.MaxDataDose1DifteriaTetano?.ToString("yyyy-MM-dd"),
                MinDataDose2DifteriaTetano = datasMinMax.MinDataDose2DifteriaTetano?.ToString("yyyy-MM-dd"),
                MaxDataDose2DifteriaTetano = datasMinMax.MaxDataDose2DifteriaTetano?.ToString("yyyy-MM-dd"),
                MinDataDose3DifteriaTetano = datasMinMax.MinDataDose3DifteriaTetano?.ToString("yyyy-MM-dd"),
                MaxDataDose3DifteriaTetano = datasMinMax.MaxDataDose3DifteriaTetano?.ToString("yyyy-MM-dd"),
                MinDataDoseReforcoDifteriaTetano = datasMinMax.MinDataDoseReforcoDifteriaTetano?.ToString("yyyy-MM-dd"),
                MaxDataDoseReforcoDifteriaTetano = datasMinMax.MaxDataDoseReforcoDifteriaTetano?.ToString("yyyy-MM-dd"),
                MinDataDose1TripliceViral = datasMinMax.MinDataDose1TripliceViral?.ToString("yyyy-MM-dd"),
                MaxDataDose1TripliceViral = datasMinMax.MaxDataDose1TripliceViral?.ToString("yyyy-MM-dd"),
                MinDataDose2TripliceViral = datasMinMax.MinDataDose2TripliceViral?.ToString("yyyy-MM-dd"),
                MaxDataDose2TripliceViral = datasMinMax.MaxDataDose2TripliceViral?.ToString("yyyy-MM-dd"),
                MinDataDose1Covid = datasMinMax.MinDataDose1Covid?.ToString("yyyy-MM-dd"),
                MaxDataDose1Covid = datasMinMax.MaxDataDose1Covid?.ToString("yyyy-MM-dd"),
                MinDataDose2Covid = datasMinMax.MinDataDose2Covid?.ToString("yyyy-MM-dd"),
                MaxDataDose2Covid = datasMinMax.MaxDataDose2Covid?.ToString("yyyy-MM-dd"),
                MinDataDose3Covid = datasMinMax.MinDataDose3Covid?.ToString("yyyy-MM-dd"),
                MaxDataDose3Covid = datasMinMax.MaxDataDose3Covid?.ToString("yyyy-MM-dd"),
                MinDataDoseReforco1Covid = datasMinMax.MinDataDoseReforco1Covid?.ToString("yyyy-MM-dd"),
                MaxDataDoseReforco1Covid = datasMinMax.MaxDataDoseReforco1Covid?.ToString("yyyy-MM-dd"),
                MinDataDoseReforco2Covid = datasMinMax.MinDataDoseReforco2Covid?.ToString("yyyy-MM-dd"),
                MaxDataDoseReforco2Covid = datasMinMax.MaxDataDoseReforco2Covid?.ToString("yyyy-MM-dd"),
                MinDataDoseUnicaFebreAmarela = datasMinMax.MinDataDoseUnicaFebreAmarela?.ToString("yyyy-MM-dd"),

ControleVacinas - MVC ASP-NET/Views/ListaDeCadastros/ApagarConfirmacao.cshtml
@model ListaDeCadastrosModel
@{
    ViewData["Title"] = "Confirmar exclusão";
}

<div class="titulo-apagar-confirmacao-container">
    <div>APAGAR COFIRMAÇÃO</div>
</div>

<div class="editar-apagar-confirmacao-container">
    <table style="border-collapse: collapse; width: 100%; table-layout: fixed;">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Número de Matrícula</th>
                <th>Data de Nascimento</th>
                <th>Setor</th>
                <th>Cargo</th>
                <th>Situação Vacinação</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Nome</td>
                <td>@Model.NumMatricula</td>
                <td>@Model.DataNascimento.ToString("dd/MM/yyyy")</td>
                <td>@Model.Setor</td>
                <td>@Model.Cargo</td>
                <td>
                    @switch (Model.SituacaoVacinacao)
                    {
                        case ControleVacinas___MVC_ASP_NET.Enums.SituacaoVacinacaoEnum.VacinacaoCompleta:
                            @:Vacinação completa
                            break;
                        case ControleVacinas___MVC_ASP_NET.Enums.SituacaoVacinacaoEnum.VacinacaoAusente:
                            @:Vacinação ausente
                            break;
                        case ControleVacinas___MVC_ASP_NET.Enums.SituacaoVacinacaoEnum.VacinacaoParcial:
                            @:Vacinação parcial
                            break;
                        default:
                            @:Situação desconhecida
                            break;
                    }
                </td>
            </tr>
            <!-- Adicione mais linhas conforme necessário -->
        </tbody>
    </table>


    <div class="d-flex">

        <a class="btn btn-secondary btn-block  me-2" asp-controller="ListaDeCadastros" asp-action="Index" role="button">Cancelar exclusão</a>
        @* <a class="btn btn-danger btn-block" asp-controller="ListaDeCadastros" asp-action="Apagar" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a> *@

        <form asp-controller="ListaDeCadastros" asp-action="PseudoApagarUsuarioPadrao" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-danger btn-block">Confirmar exclusão</button>
        </form>

    </div>
</div>

ControleVacinas - MVC ASP-NET/Views/ListaDeCadastros/Cadastrar.cshtml
@model ListaDeCadastrosModel
@{
    ViewData["Title"] = "Cadastro servidor";
}

<div class="text-center">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div id="alert-box" class="alert alert-success custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div id="alert-box" class="alert alert-danger custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemErro"]
        </div>
    }
</div>

<div class="titulo-cadastro-container">
    <div>CRIAR CADASTRO</div>
</div>

<div class="cadastro-servidor-container">

    <form asp-controller="ListaDeCadastros" asp-action="Cadastrar" method="post">

            <legend>Dados do Servidor</legend>
            <div class="row">
                <div class="form-group col-auto">
                    <label for="NumMatricula">Número de Matrícula</label>
                    <input type="number" asp-for="NumMatricula" class="form-control" placeholder="Digite a matricula">
                    <div id="numeroMatricula" class="form-text">Matrícula de 8 números: 45637293</div>
                    @Html.ValidationMessageFor(x => x.NumMatricula)
                </div>
                <div class="form-group col-auto">
                    <label for="Nome">Nome</label>
                    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome">
                    @Html.ValidationMessageFor(x => x.Nome)
                </div>
                <div class="form-group col-auto">
                    <label for="DataNascimento">Data de Nascimento</label>
                    <input type="date" asp-for="DataNascimento" class="form-control">
                    @Html.ValidationMessageFor(x => x.DataNascimento)
                </div>
                <div class="form-group col-auto">
                    <label for="Setor">Setor</label>
                    <input type="text" asp-for="Setor" class="form-control" placeholder="Digite o setor">
                    @Html.ValidationMessageFor(x => x.Setor)
                </div>
                <div class="form-group col-auto">
                    <label for="Cargo">Cargo</label>
                    <input type="text" asp-for="Cargo" class="form-control" placeholder="Digite o cargo">
                    @Html.ValidationMessageFor(x => x.Cargo)
                </div>       
            </div>


            <legend>Vacinação do servidor</legend>         
                <div class="row"> 

                    <div class="col-auto">

                    <p class="subtitulo-vacinas">HEPATITE B (HB)</p>
                    <div class="form-group col-auto">
                        <label for="DataDose1HepatiteB">Data 1ªDose</label>
                        <input type="date" asp-for="DataDose1HepatiteB" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose2HepatiteB">Data 2ªDose</label>
                        <input type="date" asp-for="DataDose2HepatiteB" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose3HepatiteB">Data 3ªDose</label>
                        <input type="date" asp-for="DataDose3HepatiteB" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDoseReforcoHepatiteB">Data Dose de Reforço</label>
                        <input type="date" asp-for="DataDoseReforcoHepatiteB" class="form-control">
                    </div>

                    </div>

                    <div class="col-auto">

                <p class="subtitulo-vacinas">EXAME ANTI-HBS</p>
                <div class="form-group col-auto">
                        <label for="DataExameAntiHBS">Data do Exame</label>
                        <input type="date" asp-for="DataExameAntiHBS" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="ResultadoExameAntiHBS">Resultado</label>
                        <input type="text" asp-for="ResultadoExameAntiHBS" class="form-control">
                        <div id="ResultadoExameAntiHBS" class="form-text">Resultado: Positivo/Negativo</div>
                    </div>

                    </div>

                <div class="col-auto">

                <p class="subtitulo-vacinas">DIFTERIA E TÉTANO (DT)</p>
                
                    <div class="form-group col-auto">
                        <label for="DataDose1DifteriaTetano">Data 1ªDose</label>
                        <input type="date" asp-for="DataDose1DifteriaTetano" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose2DifteriaTetano">Data 2ªDose</label>
                        <input type="date" asp-for="DataDose2DifteriaTetano" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose3DifteriaTetano">Data 3ªDose</label>
                        <input type="date" asp-for="DataDose3DifteriaTetano" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDoseReforcoDifteriaTetano">Data Dose de Reforço</label>
                        <input type="date" asp-for="DataDoseReforcoDifteriaTetano" class="form-control">
                    </div>
                </div>

                <div class="col-auto">

                <p class="subtitulo-vacinas">TRÍPLICE VIRAL</p>
                
                    <div class="form-group col-auto">
                        <label for="DataDose1TripliceViral">Data 1ªDose</label>
                        <input type="date" asp-for="DataDose1TripliceViral" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose2TripliceViral">Data 2ªDose</label>
                        <input type="date" asp-for="DataDose2TripliceViral" class="form-control">
                    </div>
                </div>

                <div class="col-auto">

                <p class="subtitulo-vacinas">COVID-19</p>
                
                    <div class="form-group col-auto">
                        <label for="DataDose1Covid">Data 1ªDose</label>
                        <input type="date" asp-for="DataDose1Covid" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose2Covid">Data 2ªDose</label>
                        <input type="date" asp-for="DataDose2Covid" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDose3Covid">Data 3ªDose</label>
                        <input type="date" asp-for="DataDose3Covid" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDoseReforco1Covid">Data 1ª Dose de Reforço</label>
                        <input type="date" asp-for="DataDoseReforco1Covid" class="form-control">
                    </div>
                    <div class="form-group col-auto">
                        <label for="DataDoseReforco1Covid">Data 2ª Dose de Reforço</label>
                        <input type="date" asp-for="DataDoseReforco2Covid" class="form-control">
                    </div>
                </div>

                <div class="col-auto">

                <p class="subtitulo-vacinas">FEBRE AMARELA</p>
                
                    <div class="form-group col-auto">
                        <label for="DataDoseUnicaFebreAmarela">Data Dose Única</label>
                        <input type="date" asp-for="DataDoseUnicaFebreAmarela" class="form-control">
                    </div>
                </div>

                <div class="col-auto">

                <p class="subtitulo-vacinas">INFLUENZA</p>

                <div class="form-group col-auto">
                        <label for="DataDoseAnualInfluenza">Data Dose Anual</label>
                        <input type="date" asp-for="DataDoseAnualInfluenza" class="form-control">
                </div>

                </div>

                </div>

        <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
        <a class="btn btn-secondary btn-block" asp-controller="ListaDeCadastros" asp-action="Index" role="button">Voltar</a>
    </form>

</div>

ControleVacinas - MVC ASP-NET/Views/ListaDeCadastros/RelatorioPdf.cshtml
@model List<ListaDeCadastrosModel>
@{
    ViewData["Title"] = "Relatório de cadastros";
}

<div class="titulo-relatorio-pdf-container">
    <div>RELATÓRIO DOS SERVIDORES VACINADOS</div>
</div>

<div class="relatorio-pdf-container">

@*     <div>
        <h3>Visualização do Relatório</h3>
        @Html.Partial("_TabelaRelatorio", Model)
    </div>
 *@

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="ListaDeCadastros" asp-action="GerarRelatorio">
            Salvar PDF (salvo no servirdor)
        </a>

        <a class="btn btn-primary" role="button" asp-controller="ListaDeCadastros" asp-action="VisualizarRelatorio">
            Vizualizar Relatório (salvo no pc do usuario)
        </a>

        @* <button type="submit" class="btn btn-primary btn-block">Salvar pdf</button> *@
        <a class="btn btn-secondary btn-block" asp-controller="ListaDeCadastros" asp-action="Index" role="button">
            Voltar
        </a>
    </div>
</div>