ControleVacinas - MVC ASP-NET/Controllers/ListaDeUsuariosController.cs
using ControleVacinas___MVC_ASP_NET.Filters;
using ControleVacinas___MVC_ASP_NET.Models;
using ControleVacinas___MVC_ASP_NET.Repositorio;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ControleVacinas___MVC_ASP_NET.Controllers
{
    [PaginaRestritaSomenteAdmin]
    public class ListaDeUsuariosController : Controller
    {
        private readonly IListaDeUsuariosRepositorio _listaDeUsuariosRepositorio;
        private readonly IListaDeCadastrosRepositorio _listaDeCadastrosRepositorio; 
        public ListaDeUsuariosController(IListaDeUsuariosRepositorio listaDeUsuariosRepositorio,
                                         IListaDeCadastrosRepositorio listaDeCadastrosRepositorio)
        {
            _listaDeUsuariosRepositorio = listaDeUsuariosRepositorio;
            _listaDeCadastrosRepositorio = listaDeCadastrosRepositorio;
        }

        public IActionResult Index()
        {
            List<ListaDeUsuariosModel> listaDeUsuarios = _listaDeUsuariosRepositorio.BuscarTodos();
            return View(listaDeUsuarios);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(ListaDeUsuariosModel listaDeUsuariosModel)
        {
            try
            {
                //Debug                 
                if (ModelState.IsValid)
                {
                    listaDeUsuariosModel = _listaDeUsuariosRepositorio.Adicionar(listaDeUsuariosModel);                                                                         

                    TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";
                    return RedirectToAction("Index");
                } else {
                    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                    {
                        Console.WriteLine($"Erro: {error.ErrorMessage}");
                    }
                    return View(listaDeUsuariosModel);
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível realizar o cadastro, tente novamente! Erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult ListarCadastrosPorUsuarioId(int id)
        {
            //List<ListaDeCadastrosModel> cadastros = _listaDeCadastrosRepositorio.BuscarTodosOsCadastrosDoUsuario(id);
            List<ListaDeCadastrosModel> cadastros = _listaDeCadastrosRepositorio.BuscarTodos(id);
            return PartialView("_CadastrosUsuario", cadastros);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _listaDeUsuariosRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Usuario apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não foi possível apagar o usuário, tente novamente!";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível apagar o usuário, tente novamente! Erro:{erro.Message}";
                return RedirectToAction("Index");

            }
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ListaDeUsuariosModel listaDeUsuariosModel = _listaDeUsuariosRepositorio.ListarPorId(id);
            return View(listaDeUsuariosModel);
        }

        public IActionResult Editar(int id)
        {
            ListaDeUsuariosModel listaDeUsuariosModel = _listaDeUsuariosRepositorio.ListarPorId(id);
            return View(listaDeUsuariosModel);
        }

        [HttpPost]
        public IActionResult Editar(ListaDeUsuariosSemSenhaModel listaDeUsuariosSemSenhaModel)
        {
            try
            {
                ListaDeUsuariosModel usuario = null;

                if (ModelState.IsValid)
                {
                    usuario = new ListaDeUsuariosModel()
                    {
                        Id = listaDeUsuariosSemSenhaModel.Id,
                        Nome = listaDeUsuariosSemSenhaModel.Nome,
                        Login = listaDeUsuariosSemSenhaModel.Login,
                        Email = listaDeUsuariosSemSenhaModel.Email,
                        Perfil = listaDeUsuariosSemSenhaModel.Perfil
                    };

                    usuario = _listaDeUsuariosRepositorio.Atualizar(usuario);
                    TempData["MensagemSucesso"] = "Usuário alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(usuario);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível atualizar o usuário, tente novamente! Erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleVacinas - MVC ASP-NET/Views/ListaDeUsuarios/ApagarConfirmacao.cshtml
@model ListaDeUsuariosModel
@{
    ViewData["Title"] = "Confirmar exclusão";
}

<div class="text-center">
    <h3 class="display-4">Deseja realmente apagar o usuario:</h3>
    <h3 class="display-4">@Model.Nome, @Model.Login, @Model.Email, (@Model.Perfil == 1 ? Administrador : Padrão) ?</h3>
</div>

<br />

<a class="btn btn-primary btn-block" asp-controller="ListaDeUsuarios" asp-action="Index" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-controller="ListaDeUsuarios" asp-action="Apagar" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

ControleVacinas - MVC ASP-NET/Views/ListaDeUsuarios/Cadastrar.cshtml
@using ControleVacinas___MVC_ASP_NET.Enums
@model ListaDeUsuariosModel
@{
    ViewData["Title"] = "Criar cadastro usuário";
}

<div class="text-center">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div id="alert-box" class="alert alert-success custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div id="alert-box" class="alert alert-danger custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemErro"]
        </div>
    }
</div>

<div class="text-center">
    <h1 class="display-4">Criar usuário</h1>
    <p>Usuários</p>
</div>

<br />

<form asp-controller="ListaDeUsuarios" asp-action="Cadastrar" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do usuário">
        <div id="nome" class="form-text"> </div>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="login" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Insira o login do usuário">
        <div id="login" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="senha" class="form-label">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Insira a senha do usuário">
        <div id="senha" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Senha)
    </div>

    <div class="form-group">
        <label for="email" class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Insira o email do usuário">
        <div id="email" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">   
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="ListaDeUsuarios" asp-action="Index" role="button">Voltar</a>

</form>

ControleVacinas - MVC ASP-NET/Views/ListaDeUsuarios/Editar.cshtml
@using ControleVacinas___MVC_ASP_NET.Enums
@model ListaDeUsuariosModel
@{
    ViewData["Title"] = "Editar Usuário";
}

<div class="text-center">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div id="alert-box" class="alert alert-success custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div id="alert-box" class="alert alert-danger custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemErro"]
        </div>
    }
</div>

<div class="text-center">
    <h1 class="display-4">Editar usuário</h1>    
</div>

<br />

<form asp-controller="ListaDeUsuarios" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do usuario">
        <div id="nome" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="login" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Insira o login do usuário">
        <div id="login" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="email" class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Insira o email do usuario">
        <div id="email" class="form-text"></div>
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">   
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="ListaDeUsuarios" asp-action="Index" role="button">Voltar</a>

</form>

ControleVacinas - MVC ASP-NET/Views/ListaDeUsuarios/Index.cshtml
@model List<ListaDeUsuariosModel>
@{
    ViewData["Title"] = "Lista de usuários";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary role="button" asp-controller="ListaDeUsuarios" asp-action="Cadastrar" >Adicionar novo usuário</a>
    </div>

    <br />

    @if(TempData["MensagemSucesso"] != null)
    {
        <div id="alert-box" class="alert alert-success custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div id="alert-box" class="alert alert-danger custom-alert" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemErro"]
        </div>
    }    

    <br />

<h1 class="display-4">Lista de usuários</h1>

    <table class="table table-striped table-hover table-bordered table-sm" id="TabelaListaDeUsuarios">
        <thead>
            <tr>
                <th scope="col">#</th>                
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">Email</th>
                <th scope="col">Perfil</th>
                <th scope="col">Total de Cadastros</th>
                <th scope="col">Data de cadastro</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @if(Model !=null && Model.Any())
            {
                foreach (ListaDeUsuariosModel listaDeUsuariosModel in Model)
                {
                    <tr>
                        <th scope="row">@listaDeUsuariosModel.Id</th>                        
                        <td>@listaDeUsuariosModel.Nome</td>
                        <td>@listaDeUsuariosModel.Login</td>
                        <td>@listaDeUsuariosModel.Email</td>
                        <td>@(listaDeUsuariosModel.Perfil == ControleVacinas___MVC_ASP_NET.Enums.PerfilEnum.Admin ? "Administrador" : "Padrão")</td>
                        <td>
                            <a href="javascript:" class="btn btn-success btn-sm btn-total-cadastros" usuario-id="@listaDeUsuariosModel.Id">
                                @(listaDeUsuariosModel.ListaDeCadastros != null && listaDeUsuariosModel.ListaDeCadastros.Any() ? listaDeUsuariosModel.ListaDeCadastros.Count() : 0)
                            </a>
                        </td>
                        <td>@listaDeUsuariosModel.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-secondary" asp-route-id="@listaDeUsuariosModel.Id" asp-controller="ListaDeUsuarios" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@listaDeUsuariosModel.Id" asp-controller="ListaDeUsuarios" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>                    
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="8">Nenhum usuário encontrado!</td></tr>
            }
        </tbody>
    </table>

    <div id="modalListaDeCadastrosDoUsuario" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Lista de Cadastros</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="listaDeCadastrosDoUsuario"></div>
                </div>
            </div>
        </div>
    </div>

</div>

ControleVacinas - MVC ASP-NET/Views/ListaDeUsuarios/_CadastrosUsuario.cshtml
@model List<ListaDeCadastrosModel>

<table class="table" id="TabelaListaDeCadastrosDoUsuario">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Matricula</th>
            <th scope="col">Nome</th>
            <th scope="col">Data de Nascimento</th>
            <th scope="col">Setor</th>
            <th scope="col">Cargo</th>

            <th scope="col">DT 1ªDose</th>
            <th scope="col">DT 2ªDose</th>
            <th scope="col">DT 3ªDose</th>
            <th scope="col">DT Reforço</th>

            <th scope="col">DT Exame</th>
            <th scope="col">Resultado</th>

            <th scope="col">DT 1ªDose</th>
            <th scope="col">DT 2ªDose</th>
            <th scope="col">DT 3ªDose</th>
            <th scope="col">DT Reforço</th>

            <th scope="col">DT 1ªDose</th>
            <th scope="col">DT 2ªDose</th>

            <th scope="col">DT 1ªDose</th>
            <th scope="col">DT 2ªDose</th>
            <th scope="col">DT 3ªDose</th>
            <th scope="col">DT 1ªReforço</th>
            <th scope="col">DT 2ªReforço</th>

            <th scope="col">DT Dose Única</th>
            <th scope="col">DT Dose Anual</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        @if (Model != null && Model.Any())
        {
            foreach (ListaDeCadastrosModel listaDeCadastrosModel in Model)
            {
                <tr>
                    <th scope="row">@listaDeCadastrosModel.Id</th>
                    <td>@listaDeCadastrosModel.NumMatricula</td>
                    <td>@listaDeCadastrosModel.Nome</td>
                    <td>@listaDeCadastrosModel.DataNascimento</td>
                    <td>@listaDeCadastrosModel.Setor</td>
                    <td>@listaDeCadastrosModel.Cargo</td>

                    <td>@listaDeCadastrosModel.DataDose1HepatiteB</td>
                    <td>@listaDeCadastrosModel.DataDose2HepatiteB</td>
                    <td>@listaDeCadastrosModel.DataDose3HepatiteB</td>
                    <td>@listaDeCadastrosModel.DataDoseReforcoHepatiteB</td>

                    <td>@listaDeCadastrosModel.DataExameAntiHBS</td>
                    <td>@listaDeCadastrosModel.ResultadoExameAntiHBS</td>

                    <td>@listaDeCadastrosModel.DataDose1DifteriaTetano</td>
                    <td>@listaDeCadastrosModel.DataDose2DifteriaTetano</td>
                    <td>@listaDeCadastrosModel.DataDose3DifteriaTetano</td>
                    <td>@listaDeCadastrosModel.DataDoseReforcoDifteriaTetano</td>

                    <td>@listaDeCadastrosModel.DataDose1TripliceViral</td>
                    <td>@listaDeCadastrosModel.DataDose2TripliceViral</td>

                    <td>@listaDeCadastrosModel.DataDose1Covid</td>
                    <td>@listaDeCadastrosModel.DataDose2Covid</td>
                    <td>@listaDeCadastrosModel.DataDose3Covid</td>
                    <td>@listaDeCadastrosModel.DataDoseReforco1Covid</td>
                    <td>@listaDeCadastrosModel.DataDoseReforco2Covid</td>

                    <td>@listaDeCadastrosModel.DataDoseUnicaFebreAmarela</td>

                    <td>@listaDeCadastrosModel.DataDoseAnualInfluenza</td>
                </tr>
            }
        } else {
            <tr class="odd"><td valign="top" colspan="6">Nenhum usuário encontrado!</td></tr>
        }
    </tbody>
</table>