ControleVacinas - MVC ASP-NET/Controllers/AlterarSenhaController.cs
using ControleVacinas___MVC_ASP_NET.Helper;
using ControleVacinas___MVC_ASP_NET.Models;
using ControleVacinas___MVC_ASP_NET.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleVacinas___MVC_ASP_NET.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IListaDeUsuariosRepositorio _listaDeUsuariosRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IListaDeUsuariosRepositorio listaDeUsuariosRepositorio,
                                      ISessao sessao)
        {
            _listaDeUsuariosRepositorio = listaDeUsuariosRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                ListaDeUsuariosModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if (ModelState.IsValid)
                {
                    _listaDeUsuariosRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível alterar sua senha, tente novamente. Erro: {erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

ControleVacinas - MVC ASP-NET/Views/AlterarSenha/Index.cshtml
@using ControleVacinas___MVC_ASP_NET.Enums
@model AlterarSenhaModel
@{
    ViewData["Title"] = "Alterar senha";
}

<div class="text-center">
    <h1 class="display-4">Alterar senha do usuário</h1>    
</div>

@if (TempData["MensagemSucesso"] != null)
{
    <div id="alert-box" class="alert alert-success custom-alert" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div id="alert-box" class="alert alert-danger custom-alert custom-alert" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
        @TempData["MensagemErro"]
    </div>
}

<br />

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

    <div class="form-grup">
        <label for="senhaAtual" class="form-label">Senha atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a sua senha atual">
        <div id="senhaAtual" class="form-text"> </div>
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>

    <div class="form-grup">
        <label for="novaSenha" class="form-label">Nova senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha que deseja">
        <div id="novaSenha" class="form-text"> </div>
        @Html.ValidationMessageFor(x => x.NovaSenha)
    </div>

    <div class="form-grup">
        <label for="confirmarNovaSenha" class="form-label">Confirmar nova senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Digite novamente a nova senha para confirmação">
        <div id="confirmarNovaSenha" class="form-text"> </div>
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar senha</button>
    <a class="btn btn-secondary btn-block" asp-controller="Home" asp-action="Index" role="button">Voltar</a>

</form>